CREATE TABLE users
(
    user_id  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username VARCHAR2(60),
    password VARCHAR2(1024)
);

CREATE UNIQUE INDEX user_id_pk ON users (user_id);

ALTER TABLE users
    ADD (CONSTRAINT user_id_pk PRIMARY KEY (user_id));

CREATE OR REPLACE PROCEDURE insertUser(p_username IN STRING, p_password IN STRING, p_user_id OUT NUMBER)
IS
BEGIN
    INSERT INTO users(username, password)
    VALUES (p_username, p_password);
    p_user_id := 0;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE getUser(p_username IN STRING, p_password OUT STRING, p_user_id OUT NUMBER)
IS
    v_user_count INTEGER;
BEGIN
    BEGIN
        SELECT user_id, password
        INTO p_user_id, p_password
        FROM USERS
        WHERE username = p_username;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
        p_password := NULL;
        p_user_id := NULL;
    END;
END;
/

COMMIT;